(() => {
  const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const option=(q,l)=>q.options.find(o=>o.letter===l);
  const text=(q,ls)=>ls.map(l=>option(q,l)?.text||l).join(' ');
  const concepts=[
    {re:/reflection|absorption|refraction|diffraction|multipath|signal|interference|glass|building material/i,topic:'RF & Signal Propagation',why:'Wireless and cellular signals interact with physical materials. The question context determines whether the signal is being reflected, absorbed, refracted, diffracted, or interfered with.',hook:'Glass/metal can reflect RF • dense material can absorb it'},
    {re:/subnet|cidr|vlsm|subnet mask|\/\d{1,2}\b/i,topic:'Subnetting & IP',why:'Subnetting determines which destinations are local and which require a router. Use the stated mask/CIDR and host requirement rather than a nearby networking keyword.',hook:'/24 = 255.255.255.0 • /16 = 255.255.0.0'},
    {re:/default gateway|router|routing|route\b|wan|rip\b|ospf|bgp|eigrp/i,topic:'Routing',why:'Routers make Layer 3 forwarding decisions between IP networks. Traffic for a different subnet normally goes to the default gateway.',hook:'Different subnet → default gateway → router'},
    {re:/mac address|switch|bridge|layer 2|data link|802\.1q|vlan|trunk|stp|spanning tree/i,topic:'Switching & VLANs',why:'Layer 2 forwarding uses Ethernet frames and MAC addresses. VLANs create separate Layer 2 broadcast domains.',hook:'Layer 2 = frames + MAC + switches'},
    {re:/dhcp|169\.254|apipa/i,topic:'DHCP',why:'DHCP provides host IP configuration including address, mask, gateway, and DNS. APIPA commonly indicates a failed DHCP lease.',hook:'DHCP = IP settings • APIPA = DHCP failed'},
    {re:/dns|name resolution/i,topic:'DNS',why:'DNS resolves names to IP addresses. It does not assign addresses or forward packets.',hook:'DNS = names → IP addresses'},
    {re:/nat|pat|private ip|public ip|address translation/i,topic:'NAT/PAT',why:'NAT/PAT translates addresses, commonly allowing private hosts to communicate using public addressing. Translation and routing are separate functions.',hook:'NAT translates • routing forwards'},
    {re:/tcp|udp|port\b|ssh|telnet|http|https|ldap|ldaps|snmp|smtp|imap|pop3|sip|rtp/i,topic:'Ports & Protocols',why:'Match the application/service described by the scenario to the protocol and transport behavior it requires.',hook:'Service → protocol → port'},
    {re:/wireless|wi-?fi|802\.11|access point|\bwap\b|ssid|wpa|wpa2|antenna|5ghz|2\.4ghz|gsm|mimo|eap|peap|ccmp|cellular/i,topic:'Wireless',why:'Wireless questions can test standards, authentication, encryption, antennas, roaming, or RF behavior. Identify which of those jobs the scenario is actually asking about.',hook:'Wireless: identify the job before choosing the technology'},
    {re:/fiber|cat[356]|cable|connector|rj45|sfp|gbic|multimode|single.?mode|attenuation|otdr|poe/i,topic:'Cabling & Physical',why:'Choose physical media by distance, bandwidth, connector/transceiver compatibility, power, and environment.',hook:'Layer 1 = media + signal + connector + distance'},
    {re:/topology|mesh|star|ring|bus|fault.?toler|redundan/i,topic:'Topologies',why:'Topology questions compare how devices connect and whether the design provides a central point or redundant paths.',hook:'Star = center • Mesh = redundancy'},
    {re:/firewall|attack|malware|phishing|encryption|authentication|authorization|vpn|ids|ips|nac|security|hardening/i,topic:'Security',why:'Match the security requirement to the control that directly performs that job: authentication, authorization, encryption, prevention, detection, or isolation.',hook:'Requirement → security function → control'},
    {re:/osi|layer\s*[1-7]|transport|session|presentation|application layer|network layer/i,topic:'OSI Model',why:'Identify the object/function being described: signals, frames/MAC, packets/IP, segments/ports, or application data.',hook:'L2 MAC/frames • L3 IP/packets • L4 ports/segments'},
    {re:/cloud|saas|paas|iaas|virtual|hypervisor|vswitch|virtual switch/i,topic:'Cloud & Virtualization',why:'Cloud service models differ by which layers the provider manages. Virtualization implements compute/network functions in software.',hook:'IaaS infrastructure • PaaS platform • SaaS application'},
    {re:/troubleshoot|cannot|unable|issue|problem|fails|failure|intermittent|ping|traceroute|ipconfig|netstat|baseline/i,topic:'Troubleshooting',why:'Use the symptoms and what has already been verified to identify the most likely layer/cause, then choose the least disruptive verification or fix.',hook:'Evidence → likely cause → verify → fix'}
  ];
  const distractors=[
    [/\babsorption\b/i,'Absorption means a material takes in RF energy and weakens the signal passing through it. That can cause attenuation, but it is not the best match when the scenario emphasizes glass surfaces that bounce RF energy and create reflected paths.'],
    [/\breflection\b/i,'Reflection occurs when RF energy bounces off a surface such as glass or metal. Reflected signals can create multipath and poor cellular or Wi-Fi performance.'],
    [/\bmimo\b/i,'MIMO uses multiple antennas/spatial streams to improve wireless throughput and reliability. It does not provide cellular carrier roaming.'],
    [/ccmp|aes/i,'CCMP/AES provides wireless encryption. It protects data confidentiality but does not identify each user against Active Directory.'],
    [/\bgsm\b/i,'GSM is a cellular standard associated with broad international deployment and subscriber-based roaming; it is not a Wi-Fi antenna or encryption technology.'],
    [/eap|peap/i,'EAP/PEAP provides enterprise authentication and can be backed by RADIUS/Active Directory so users authenticate with individual credentials.'],
    [/assign.*ip|new private ip|ip address.*assign/i,'This describes address assignment, normally DHCP or static configuration, rather than the forwarding behavior in the scenario.'],
    [/dns/i,'DNS performs name resolution. It does not perform routing, switching, or IP assignment.'],
    [/dhcp/i,'DHCP supplies host IP configuration. It does not perform routing or switching.'],
    [/encrypt/i,'Encryption protects confidentiality. It is only the answer when protecting data is the requirement being tested.'],
    [/mac address/i,'MAC addresses identify Layer 2 interfaces on the local link; they are not routable Layer 3 addresses.'],
    [/switch|bridge/i,'A switch/bridge forwards Layer 2 frames by MAC address. It does not route traffic between IP networks.'],
    [/router|routing/i,'A router forwards Layer 3 traffic between networks. It is not the right fit for a purely Layer 2 function.'],
    [/firewall/i,'A firewall enforces traffic security policy; that is different from addressing, switching, routing, or name resolution.'],
    [/bus/i,'Bus uses a shared backbone rather than a central forwarding device or multiple redundant paths.'],
    [/ring/i,'Ring forms a loop; it is not the best answer for a central-device layout or maximum redundancy.'],
    [/star/i,'Star connects endpoints to a central device but does not inherently provide the multiple redundant paths of a mesh.'],
    [/mesh/i,'Mesh provides multiple redundant paths; if the requirement is simply a central forwarding point, star fits better.']
  ];
  function special(q,correct){const qt=q.question.toLowerCase(),ct=text(q,correct).toLowerCase();
    if(/glass|natural light/.test(qt)&&/cellular/.test(qt)&&/reflection/.test(ct))return{topic:'RF & Signal Propagation',why:'The clue is the building’s extensive glass. RF energy can reflect off glass surfaces instead of traveling cleanly through the environment. Those reflected copies can arrive by different paths and contribute to multipath/interference, reducing cellular signal quality and speed.',hook:'Glass + RF problems → think reflection/multipath'};
    if(/roam|international/.test(qt)&&/gsm/.test(ct))return{topic:'Cellular Technologies',why:'The requirement is national/international roaming and switching providers. Among these choices, GSM best fits because it became broadly deployed internationally and uses subscriber identity mechanisms designed to support roaming between compatible carrier networks.',hook:'International cellular roaming → GSM'};
    if(/active directory|uniquely identified|individual users/.test(qt)&&/eap|peap/.test(ct))return{topic:'Wireless Authentication',why:'The clue is individual Active Directory credentials. Enterprise WLAN authentication uses 802.1X/EAP, commonly with RADIUS connected to Active Directory. PEAP protects the authentication exchange; CCMP/AES is encryption, not user authentication.',hook:'AD credentials → 802.1X/EAP • AES → encryption'};
    if(/class c|\/24/.test(qt)&&/host|assign/.test(qt))return{topic:'Subnetting & IP',why:'A /24 contains 256 addresses. The .0 network address and .255 broadcast address are reserved, so host addresses are .1 through .254.',hook:'/24 hosts = .1–.254'};
    if(/\/16/.test(qt)&&/255\.255\.255\.0/.test(q.question))return{topic:'Subnetting & IP',why:'The intended network is /16 (255.255.0.0), but the host is configured /24 (255.255.255.0). That makes the host believe only its 172.16.25.x /24 is local instead of the entire 172.16.0.0/16 network.',hook:'/16 = 255.255.0.0'};
    if(/192\.168\.1\.0\/24/.test(q.question)&&/255\.255\.0\.0/.test(q.question))return{topic:'Subnetting & IP',why:'The workstation should use /24. With /16, it incorrectly treats other 192.168.x.x destinations as local and ARPs for them instead of sending them to the default gateway.',hook:'Mask too broad → remote networks look local'};
    if(/vlsm/i.test(q.question))return{topic:'Subnetting & IP',why:'VLSM assigns the smallest subnet that satisfies each host requirement: /28 = 14 usable, /27 = 30, /26 = 62, /25 = 126.',hook:'Size VLSM largest first; choose smallest subnet that fits'};
    return null}
  function conceptFor(q){const blob=`${q.question} ${q.options.map(o=>o.text).join(' ')}`;return concepts.find(c=>c.re.test(blob))||{topic:'Network Fundamentals',why:'The correct choice most directly satisfies the specific requirement described in the scenario.',hook:'Read the requirement first; then match the technology to its function.'}}
  function rightWhy(q,correct){return special(q,correct)||conceptFor(q)}
  function wrongWhy(q,l,correct){const o=option(q,l);if(!o)return'This choice does not satisfy the scenario.';const sp=special(q,correct);if(sp&&/glass|natural light/.test(q.question.toLowerCase())&&/absorption/i.test(o.text))return'Absorption would mean the material is taking RF energy into itself and attenuating it. In this scenario, the stronger clue is the large amount of glass, which can reflect RF and create multiple signal paths; that makes reflection the better answer.';for(const[re,msg]of distractors)if(re.test(o.text))return msg;const c=sp||conceptFor(q);return`This choice describes a different function than the scenario requires. The question is testing ${c.topic.toLowerCase()}; focus on the clues in the scenario rather than the answer term by itself.`}
  window.networkReasoning=(q,sel,correct)=>{const r=rightWhy(q,correct);return{...r,wrong:sel.filter(l=>!correct.includes(l)).map(l=>({letter:l,text:option(q,l)?.text||l,why:wrongWhy(q,l,correct)}))}};
  function reasoningHTML(q,sel,correct,ok){const r=window.networkReasoning(q,sel,correct),wrong=!ok&&r.wrong.length?`<div class="reasonblock wrongreason"><div class="reasontitle">❌ Why your choice was wrong</div>${r.wrong.map(w=>`<div><strong>${E(w.letter)}. ${E(w.text)}</strong><br>${E(w.why)}</div>`).join('<div class="reasonsep"></div>')}</div>`:'';return`${wrong}<div class="reasonblock rightreason"><div class="reasontitle">✅ Why the correct answer is right</div><div>${E(r.why)}</div></div><div class="memoryhook"><strong>🧠 Remember:</strong> ${E(r.hook)}</div><div class="reasontopic">Topic: ${E(r.topic)}</div>`}
  function installStyles(){if(document.getElementById('reasoningStyles'))return;const s=document.createElement('style');s.id='reasoningStyles';s.textContent='.reasonblock{margin-top:12px;padding:12px 13px;border-radius:11px;font-weight:500;line-height:1.5}.wrongreason{background:#2d1821;border:1px solid #673143}.rightreason{background:#102b1b;border:1px solid #315f40}.reasontitle{font-weight:900;margin-bottom:6px}.reasonsep{height:1px;background:var(--border);margin:10px 0}.memoryhook{margin-top:10px;padding:10px 12px;background:#142846;border:1px solid #315888;border-radius:11px}.reasontopic{margin-top:7px;font-size:.78rem;color:var(--muted);font-weight:700}.review-reason{margin-top:10px}';document.head.appendChild(s)}
  function patch(){installStyles();try{const orig=submitAnswer;if(typeof orig==='function'&&!orig.__reasoning){const w=function(){const q=state&&state.session&&state.session[state.idx],sel=typeof selected==='function'?selected():[],correct=q&&q.answer?q.answer.slice().sort():[],study=state&&state.mode==='study';orig();if(study&&q&&sel.length){const fb=document.getElementById('feedback');if(fb&&!fb.classList.contains('hidden'))fb.insertAdjacentHTML('beforeend',reasoningHTML(q,sel,correct,equal(sel.slice().sort(),correct)))}};w.__reasoning=true;submitAnswer=w;window.submitAnswer=w}}catch(e){console.error('Reasoning submit hook failed',e)}try{const orig=reviewMissed;if(typeof orig==='function'&&!orig.__reasoning){const w=function(){const byId=Object.fromEntries(BANK.map(q=>[q.id,q])),miss=state.responses.filter(r=>!r.ok),t=document.getElementById('sessionReview');if(!t)return;t.innerHTML=miss.length?`<h3>Missed questions</h3>`+miss.map(r=>{const q=byId[r.id];return`<div class="review-item"><strong>#${q.id}</strong> ${E(q.question)}<div class="badtxt">Your answer:<br>${answerText(q,r.selected)}</div><div class="goodtxt">Correct answer:<br>${answerText(q,r.correct)}</div><div class="review-reason">${reasoningHTML(q,r.selected,r.correct,false)}</div></div>`}).join(''):`<p class="goodtxt">Perfect session.</p>`};w.__reasoning=true;reviewMissed=w;window.reviewMissed=w}}catch(e){console.error('Reasoning review hook failed',e)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch);else patch();setTimeout(patch,250);setTimeout(patch,1000);
})();