(() => {
  const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const option=(q,l)=>q.options.find(o=>o.letter===l);
  const text=(q,ls)=>ls.map(l=>option(q,l)?.text||l).join(' ');
  const context=(q,correct=[])=>`${q.question} ${text(q,correct)}`;

  // Ordered from specific concepts to broad concepts. Patterns use word boundaries where
  // practical so words such as "providing" cannot accidentally match "routing".
  const concepts=[
    {re:/reflection|absorption|refraction|diffraction|multipath|attenuation|\brf\b|signal propagation|glass|electromagnetic/i,topic:'RF & Signal Propagation',why:'RF performance depends on how radio energy interacts with the environment. Materials and surfaces can reflect, absorb, refract, or diffract a signal, changing signal strength and path quality.',hook:'RF clue → identify what the material does to the signal'},
    {re:/multifactor|multi-factor|two-factor|2fa|authentication factor|something you know|something you have|something you are|biometric|fingerprint|retina|iris|hand geometry|smart card|security token|rsa token/i,topic:'Authentication & MFA',why:'Multifactor authentication requires factors from different categories. A password or PIN is something you know, a token or smart card is something you have, and a fingerprint or other biometric is something you are.',hook:'MFA = 2+ different factor types: know + have + are'},
    {re:/subnet|cidr|vlsm|subnet mask|supernet|\/\d{1,2}\b|host range|network address|broadcast address/i,topic:'Subnetting & IP',why:'The subnet mask/CIDR length determines the network boundary, usable host range, and whether a destination is local or must be routed.',hook:'Mask decides local vs remote'},
    {re:/default gateway|\brouter(?:s)?\b|\brouting\b|\broute(?:s)?\b|routing table|\bwan\b|\brip\b|\bospf\b|\bbgp\b|\beigrp\b|administrative distance/i,topic:'Routing',why:'Routing is a Layer 3 function. Routers choose a path between IP networks using the destination network and routing information.',hook:'Layer 3 = IP + routes + routers'},
    {re:/mac address|\bswitch(?:es|ing)?\b|\bbridge(?:s)?\b|layer 2|data link|802\.1q|\bvlan(?:s)?\b|\btrunk(?:s|ing)?\b|\bstp\b|spanning tree|broadcast domain|collision domain/i,topic:'Switching & VLANs',why:'Layer 2 devices forward Ethernet frames using MAC information. VLANs divide Layer 2 broadcast domains and trunks carry multiple VLANs between devices.',hook:'L2 = MAC/frames • VLAN = broadcast domain'},
    {re:/\bdhcp\b|169\.254|\bapipa\b|dhcp lease|dhcp scope|dhcp reservation|dhcp relay|ip helper/i,topic:'DHCP',why:'DHCP provides host IP configuration such as address, mask, default gateway, and DNS. Relay/helper functions allow requests to cross routed boundaries.',hook:'DHCP = automatic IP configuration'},
    {re:/\bdns\b|name resolution|a record|aaaa|cname|mx record|ptr record|zone transfer/i,topic:'DNS',why:'DNS maps names and service information to records such as IP addresses. The requested record type or resolution behavior is the key clue.',hook:'DNS = names ↔ records'},
    {re:/\bnat\b|\bpat\b|private ip|public ip|address translation|port translation/i,topic:'NAT/PAT',why:'NAT changes IP addressing between address realms; PAT additionally distinguishes sessions with transport-layer ports. Translation does not replace routing.',hook:'NAT translates addresses • PAT adds ports'},
    {re:/\btcp\b|\budp\b|\bport\s*\d*\b|\bssh\b|\btelnet\b|\bhttp\b|\bhttps\b|\bldap\b|\bldaps\b|\bsnmp\b|\bsmtp\b|\bimap\b|\bpop3\b|\bsip\b|\brtp\b|\bftp\b|\btftp\b|\bntp\b|\bsyslog\b/i,topic:'Ports & Protocols',why:'Protocol questions test what a service does and which transport/port behavior matches it. Identify the service first, then the protocol details.',hook:'Service → protocol → port/transport'},
    {re:/wireless|wi-?fi|802\.11|access point|\bwap\b|\bssid\b|\bwpa[23]?\b|antenna|5ghz|2\.4ghz|\bgsm\b|\blte\b|cellular|\bmimo\b|\beap\b|\bpeap\b|\bccmp\b|channel|roaming/i,topic:'Wireless',why:'Wireless questions can test standards, bands, antennas, roaming, authentication, encryption, or RF behavior. Match the requirement to the specific wireless function.',hook:'Wireless: standard ≠ auth ≠ encryption ≠ RF behavior'},
    {re:/fiber|cat[356]|cable|connector|rj45|sfp|gbic|multimode|single.?mode|otdr|poe|patch panel|transceiver|coax|plenum|straight.?through|crossover/i,topic:'Cabling & Physical',why:'Physical-layer choices depend on medium, connector/transceiver type, distance, bandwidth, power, and installation environment.',hook:'Layer 1 = media + signal + connector + distance'},
    {re:/topology|\bmesh\b|\bstar\b|\bring\b|\bbus\b|hub.?and.?spoke|fault.?toler|redundan|high availability/i,topic:'Topologies & Resiliency',why:'Topology and resiliency questions compare connection patterns, single points of failure, and redundant paths.',hook:'Star = center • Mesh = multiple paths'},
    {re:/firewall|attack|malware|phishing|encryption|authentication|authorization|\bvpn\b|\bids\b|\bips\b|\bnac\b|security|hardening|\bacl\b|radius|tacacs|\baaa\b|certificate|802\.1x|least privilege|segmentation/i,topic:'Network Security',why:'Security controls have different jobs: identify users, authorize access, encrypt data, filter traffic, detect attacks, isolate systems, or reduce attack surface.',hook:'Requirement → security function → control'},
    {re:/\bosi\b|layer\s*[1-7]|transport layer|session layer|presentation layer|application layer|network layer|physical layer/i,topic:'OSI Model',why:'OSI questions are solved by identifying the function or PDU: signals at Layer 1, frames/MAC at Layer 2, packets/IP at Layer 3, and ports/segments at Layer 4.',hook:'L2 frames/MAC • L3 packets/IP • L4 segments/ports'},
    {re:/cloud|\bsaas\b|\bpaas\b|\biaas\b|virtual|hypervisor|vswitch|virtual switch|\bsdn\b|\bnfv\b|container/i,topic:'Cloud & Virtualization',why:'Cloud and virtualization questions distinguish what is virtualized and which layers are managed by the customer versus the provider.',hook:'IaaS infrastructure • PaaS platform • SaaS app'},
    {re:/\bqos\b|quality of service|latency|jitter|packet loss|traffic shaping|policing|\bdscp\b|\bcos\b/i,topic:'Performance & QoS',why:'QoS manages how traffic is classified, prioritized, queued, shaped, or policed so delay-sensitive applications receive appropriate treatment.',hook:'Voice/video care about latency + jitter + loss'},
    {re:/monitor|baseline|\bsnmp\b|netflow|packet capture|syslog|performance monitor|availability|utilization/i,topic:'Monitoring & Operations',why:'Monitoring questions focus on observing device health, traffic, logs, or performance over time. A baseline gives a normal reference for comparison.',hook:'Baseline = normal • monitoring = detect change'},
    {re:/load balanc|proxy|reverse proxy|content filter|caching|\bcdn\b|application delivery/i,topic:'Network Services & Appliances',why:'Network appliances are selected by function: distributing load, proxying requests, filtering content, caching data, or accelerating delivery.',hook:'Name the traffic job → choose the appliance'},
    {re:/troubleshoot|cannot|unable|issue|problem|fails|failure|intermittent|\bping\b|traceroute|ipconfig|netstat|nslookup|\bdig\b|\barp\b|pathping|baseline/i,topic:'Troubleshooting',why:'Troubleshooting questions reward using the symptoms and already-known facts to isolate the most likely layer/cause before making changes.',hook:'Evidence → isolate → verify → fix'}
  ];

  const distractors=[
    [/stronger password|password policy/i,'A stronger password improves the quality of the knowledge factor, but it is still only something you know. Pairing it with a biometric gives two factor types; check whether another choice satisfies the requested factors more directly and completely.'],
    [/hand geometry|fingerprint|retina|iris|biometric/i,'A biometric is an inherence factor: something you are. For MFA, it must be combined with a different factor category such as a token (something you have) or password (something you know).'],
    [/smart card|rsa token|security token/i,'A smart card or authentication token is a possession factor: something you have. It contributes to MFA only when paired with a different factor type.'],
    [/\babsorption\b/i,'Absorption means a material takes RF energy into itself and attenuates the signal. Choose it when the scenario points to signal energy being absorbed by the material rather than bounced or redirected.'],
    [/\breflection\b/i,'Reflection means RF energy bounces off a surface. It is especially relevant with reflective materials and can produce multipath.'],
    [/\bmimo\b/i,'MIMO uses multiple antennas/spatial streams to improve wireless throughput/reliability. It does not provide cellular carrier roaming.'],
    [/ccmp|aes/i,'CCMP/AES provides wireless encryption. It protects data but does not identify individual users against Active Directory.'],
    [/\bgsm\b/i,'GSM is a cellular technology associated with broad international deployment and roaming; it is not a Wi-Fi antenna or encryption mechanism.'],
    [/eap|peap/i,'EAP/PEAP is used for enterprise authentication and can work with RADIUS/Active Directory for individual credentials.'],
    [/assign.*ip|new private ip|ip address.*assign/i,'This describes address assignment, normally DHCP or static configuration, not packet forwarding.'],
    [/\bdns\b/i,'DNS resolves names/records. It does not route packets, switch frames, or assign IP configuration.'],
    [/\bdhcp\b/i,'DHCP provides host IP configuration. It does not perform routing or switching.'],
    [/encrypt/i,'Encryption protects confidentiality. It is only correct when protecting the data itself is the requirement.'],
    [/mac address/i,'MAC addresses are Layer 2 identifiers used for local frame delivery; they are not routable Layer 3 addresses.'],
    [/\bswitch(?:es|ing)?\b|\bbridge(?:s)?\b/i,'A switch/bridge primarily forwards Layer 2 frames using MAC information.'],
    [/\brouter(?:s)?\b|\brouting\b/i,'A router forwards Layer 3 traffic between IP networks.'],
    [/firewall/i,'A firewall filters traffic according to security policy; that differs from addressing, switching, routing, or name resolution.'],
    [/\bbus\b/i,'Bus uses a shared backbone rather than a central forwarding device or many redundant paths.'],
    [/\bring\b/i,'Ring forms a loop rather than a central-device star or highly redundant mesh.'],
    [/\bstar\b/i,'Star connects endpoints to a central device but does not inherently provide multiple redundant paths.'],
    [/\bmesh\b/i,'Mesh provides multiple redundant paths; it is not simply the central-device layout of a star.']
  ];

  function special(q,correct){const qt=q.question.toLowerCase(),ct=text(q,correct).toLowerCase();
    if(/fingerprint|hand geometry|biometric|authentication factor|multifactor|multi-factor|two-factor/.test(`${qt} ${ct}`)&&/rsa|token|smart card/.test(`${qt} ${ct}`))return{topic:'Authentication & MFA',why:'This question is about authentication factor categories. A fingerprint or hand-geometry scan is something you are (biometric/inherence), while an RSA authentication token is something you have (possession). Combining different factor types provides multifactor authentication; simply making a password stronger does not create a new factor type.',hook:'Password = KNOW • Token = HAVE • Biometric = ARE'};
    if(/glass|natural light/.test(qt)&&/cellular/.test(qt)&&/reflection/.test(ct))return{topic:'RF & Signal Propagation',why:'The clue is the building’s extensive glass. RF energy can reflect from glass surfaces, creating additional signal paths. Those reflected copies can contribute to multipath/interference and reduce cellular signal quality and throughput.',hook:'Glass + RF issue → reflection/multipath'};
    if(/roam|international/.test(qt)&&/gsm/.test(ct))return{topic:'Cellular Technologies',why:'The requirement is national/international roaming and switching providers. Among these choices, GSM best fits because it became broadly deployed internationally and supports subscriber-based roaming between compatible carrier networks.',hook:'International cellular roaming → GSM'};
    if(/active directory|uniquely identified|individual users/.test(qt)&&/eap|peap/.test(ct))return{topic:'Wireless Authentication',why:'The key clue is individual Active Directory credentials. Enterprise WLANs use 802.1X/EAP with an authentication server such as RADIUS tied to AD. PEAP protects the authentication exchange; CCMP/AES is encryption, not identity authentication.',hook:'AD credentials → 802.1X/EAP • AES → encryption'};
    if(/class c|\/24/.test(qt)&&/host|assign/.test(qt))return{topic:'Subnetting & IP',why:'A /24 contains 256 addresses. The .0 network address and .255 broadcast address are reserved, leaving .1 through .254 usable for hosts.',hook:'/24 hosts = .1–.254'};
    if(/\/16/.test(qt)&&/255\.255\.255\.0/.test(q.question))return{topic:'Subnetting & IP',why:'The intended network is /16 (255.255.0.0), but the host is configured /24 (255.255.255.0). That makes the host treat only its local /24 as directly connected instead of the entire intended /16.',hook:'/16 = 255.255.0.0'};
    if(/192\.168\.1\.0\/24/.test(q.question)&&/255\.255\.0\.0/.test(q.question))return{topic:'Subnetting & IP',why:'The workstation should use /24. With /16 it incorrectly treats other 192.168.x.x destinations as local and ARPs for them instead of sending them to the default gateway.',hook:'Mask too broad → remote networks look local'};
    if(/vlsm/i.test(q.question))return{topic:'Subnetting & IP',why:'VLSM assigns the smallest subnet that still satisfies each host requirement. /28 gives 14 usable hosts, /27 gives 30, /26 gives 62, and /25 gives 126.',hook:'VLSM: choose the smallest subnet that fits'};
    return null}

  function conceptFor(q,correct){const blob=context(q,correct);return concepts.find(c=>c.re.test(blob))||{topic:'Network Fundamentals',why:'The correct answer is the option whose function most directly satisfies the requirement stated in the scenario.',hook:'Read the requirement first; then match the technology to that function.'}}
  function rightWhy(q,correct){return special(q,correct)||conceptFor(q,correct)}
  function wrongWhy(q,l,correct){const o=option(q,l);if(!o)return'This choice does not satisfy the scenario.';const sp=special(q,correct);if(sp&&sp.topic==='Authentication & MFA'&&/stronger password|password policy/i.test(o.text))return'A stronger password is still only one knowledge factor (something you know). The biometric adds an inherence factor, but the exam is testing factor categories: the correct choice combines a biometric (something you are) with an RSA token (something you have), giving two clearly distinct factors.';if(sp&&/glass|natural light/.test(q.question.toLowerCase())&&/absorption/i.test(o.text))return'Absorption would mean the material takes RF energy into itself and weakens the signal. Here the clue is extensive glass; reflection and the resulting multipath are the better match to the scenario.';for(const[re,msg]of distractors)if(re.test(o.text))return msg;const c=sp||conceptFor(q,correct);return`This choice does not match the requirement being tested. Focus on ${c.topic.toLowerCase()} and compare the function of this option with the function of the correct answer.`}

  window.networkReasoning=(q,sel,correct)=>{const r=rightWhy(q,correct);return{...r,wrong:sel.filter(l=>!correct.includes(l)).map(l=>({letter:l,text:option(q,l)?.text||l,why:wrongWhy(q,l,correct)}))}};
  function reasoningHTML(q,sel,correct,ok){const r=window.networkReasoning(q,sel,correct),wrong=!ok&&r.wrong.length?`<div class="reasonblock wrongreason"><div class="reasontitle">❌ Why your choice was wrong</div>${r.wrong.map(w=>`<div><strong>${E(w.letter)}. ${E(w.text)}</strong><br>${E(w.why)}</div>`).join('<div class="reasonsep"></div>')}</div>`:'';return`${wrong}<div class="reasonblock rightreason"><div class="reasontitle">✅ Why the correct answer is right</div><div>${E(r.why)}</div></div><div class="memoryhook"><strong>🧠 Remember:</strong> ${E(r.hook)}</div><div class="reasontopic">Topic: ${E(r.topic)}</div>`}
  function installStyles(){if(document.getElementById('reasoningStyles'))return;const s=document.createElement('style');s.id='reasoningStyles';s.textContent='.reasonblock{margin-top:12px;padding:12px 13px;border-radius:11px;font-weight:500;line-height:1.5}.wrongreason{background:#2d1821;border:1px solid #673143}.rightreason{background:#102b1b;border:1px solid #315f40}.reasontitle{font-weight:900;margin-bottom:6px}.reasonsep{height:1px;background:var(--border);margin:10px 0}.memoryhook{margin-top:10px;padding:10px 12px;background:#142846;border:1px solid #315888;border-radius:11px}.reasontopic{margin-top:7px;font-size:.78rem;color:var(--muted);font-weight:700}.review-reason{margin-top:10px}';document.head.appendChild(s)}
  function patch(){installStyles();try{const orig=submitAnswer;if(typeof orig==='function'&&!orig.__reasoning){const w=function(){const q=state&&state.session&&state.session[state.idx],sel=typeof selected==='function'?selected():[],correct=q&&q.answer?q.answer.slice().sort():[],study=state&&state.mode==='study';orig();if(study&&q&&sel.length){const fb=document.getElementById('feedback');if(fb&&!fb.classList.contains('hidden'))fb.insertAdjacentHTML('beforeend',reasoningHTML(q,sel,correct,equal(sel.slice().sort(),correct)))}};w.__reasoning=true;submitAnswer=w;window.submitAnswer=w}}catch(e){console.error('Reasoning submit hook failed',e)}try{const orig=reviewMissed;if(typeof orig==='function'&&!orig.__reasoning){const w=function(){const byId=Object.fromEntries(BANK.map(q=>[q.id,q])),miss=state.responses.filter(r=>!r.ok),t=document.getElementById('sessionReview');if(!t)return;t.innerHTML=miss.length?`<h3>Missed questions</h3>`+miss.map(r=>{const q=byId[r.id];return`<div class="review-item"><strong>#${q.id}</strong> ${E(q.question)}<div class="badtxt">Your answer:<br>${answerText(q,r.selected)}</div><div class="goodtxt">Correct answer:<br>${answerText(q,r.correct)}</div><div class="review-reason">${reasoningHTML(q,r.selected,r.correct,false)}</div></div>`}).join(''):`<p class="goodtxt">Perfect session.</p>`};w.__reasoning=true;reviewMissed=w;window.reviewMissed=w}}catch(e){console.error('Reasoning review hook failed',e)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch);else patch();setTimeout(patch,250);setTimeout(patch,1000);
})();